/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poligonos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;



class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".txt");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Text documents (*.txt)";
        }
    } 
/**
 *
 * @author Edgar-pc
 */
public class JAplicacion extends javax.swing.JFrame {

    /**
     * Creates new form JAplicacion
   
     */
    public static ListaPuntos listaDePuntos= new ListaPuntos();
    public static ListaPoligonos listaDePoligonos= new ListaPoligonos();
    public static ListaPoligonos listaDeSubPoligonos= new ListaPoligonos();
    public static ListaRectas listaDeRectas = new ListaRectas();
    public static boolean mayor ;
    public static boolean rango;
    
    //
   
            
    
    private static JAplicacion p;

    public static JAplicacion getInstance() {
        if (p == null) {
            p = new JAplicacion();  
        }
        return p;
    }

    String file;
    
    private static ArrayList<Punto> puntos;
    
    public static ArrayList<Punto> getPuntos(){
        if(puntos==null)
            puntos = new ArrayList();
        return puntos;    
    }
    
    
    
    
    
    
    public JAplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jFrame1 = new javax.swing.JFrame();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsola = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButtonMostrarLista = new javax.swing.JButton();
        jButtonMostrarPuntos = new javax.swing.JButton();
        jButtonCrearRectas = new javax.swing.JButton();
        jButtonCrearPoligonos = new javax.swing.JButton();
        jButtonCrearSubPoligono = new javax.swing.JButton();
        jButtonListaSubPoligonos = new javax.swing.JButton();
        jButtonMenorPerimetro = new javax.swing.JButton();
        jButtonMayorPerimetro = new javax.swing.JButton();
        jButtonPoligonoPorIndice = new javax.swing.JButton();
        jButtonRangoPerimetro = new javax.swing.JButton();
        jButtonColaterales = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemCargarPuntos = new javax.swing.JMenuItem();
        jMenuItemCargarPorDefecto = new javax.swing.JMenuItem();

        fileChooser.setDialogTitle("Ventana abierta");
        fileChooser.setFileFilter(new MyCustomFilter());

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea2.setText(listaDePoligonos.toString());
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 234, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jTextPane1);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controlador de Poligonos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consola", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTextAreaConsola.setColumns(20);
        jTextAreaConsola.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsola);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jButtonMostrarLista.setText("Mostrar Lista de Poligonos");
        jButtonMostrarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarListaActionPerformed(evt);
            }
        });

        jButtonMostrarPuntos.setText("Mostrar Lista de Puntos");
        jButtonMostrarPuntos.setToolTipText("");
        jButtonMostrarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarPuntosActionPerformed(evt);
            }
        });

        jButtonCrearRectas.setText("Crear Rectas");
        jButtonCrearRectas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearRectasActionPerformed(evt);
            }
        });

        jButtonCrearPoligonos.setText("Crear Poligonos");
        jButtonCrearPoligonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPoligonosActionPerformed(evt);
            }
        });

        jButtonCrearSubPoligono.setText("Crear Sub-Poligono");
        jButtonCrearSubPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearSubPoligonoActionPerformed(evt);
            }
        });

        jButtonListaSubPoligonos.setText("Obtener lista de Sub-Poligonos");

        jButtonMenorPerimetro.setText("Obtener Lista Menor Perimetros");
        jButtonMenorPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenorPerimetroActionPerformed(evt);
            }
        });

        jButtonMayorPerimetro.setText("Obtener Lista Mayor Perimetros");
        jButtonMayorPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMayorPerimetroActionPerformed(evt);
            }
        });

        jButtonPoligonoPorIndice.setText("Mostrar Poligono por Ind.");

        jButtonRangoPerimetro.setText("Mostrar Poligono Rango Perimetro");
        jButtonRangoPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRangoPerimetroActionPerformed(evt);
            }
        });

        jButtonColaterales.setText("Verificar Poligonos Colaterales");
        jButtonColaterales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColateralesActionPerformed(evt);
            }
        });

        jButton1.setText("Mostrar wea");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jButtonMostrarLista)
                        .addComponent(jButtonMostrarPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCrearRectas, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCrearPoligonos)
                        .addComponent(jButtonCrearSubPoligono)
                        .addComponent(jButtonListaSubPoligonos)
                        .addComponent(jButtonMenorPerimetro)
                        .addComponent(jButtonMayorPerimetro))
                    .addComponent(jButtonPoligonoPorIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRangoPerimetro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonColaterales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonColaterales, jButtonCrearPoligonos, jButtonCrearRectas, jButtonCrearSubPoligono, jButtonListaSubPoligonos, jButtonMayorPerimetro, jButtonMenorPerimetro, jButtonMostrarLista, jButtonMostrarPuntos, jButtonPoligonoPorIndice, jButtonRangoPerimetro});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMostrarLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrarPuntos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCrearRectas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCrearPoligonos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCrearSubPoligono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListaSubPoligonos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMenorPerimetro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMayorPerimetro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPoligonoPorIndice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRangoPerimetro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonColaterales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jToggleButton1.setText("lista rectas");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Puntos");

        jMenu3.setText("Cargar Puntos...");

        jMenuItemCargarPuntos.setText("Desde Archivo");
        jMenuItemCargarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarPuntosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCargarPuntos);

        jMenuItemCargarPorDefecto.setText("Por Defecto");
        jMenuItemCargarPorDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarPorDefectoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCargarPorDefecto);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarListaActionPerformed
        // TODO add your handling code here:
        JListaPoligonos.getInstance().setVisible(true);
      
        //jDialog1.setVisible(true);
        
        String sub="";
        if (listaDeSubPoligonos.getSize()!=0){
            sub="Lista de SubPoligonos:\n"+listaDeSubPoligonos;
            
        }
        
        
        
        jTextAreaConsola.setText(listaDePoligonos.toString()+sub);
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonMostrarListaActionPerformed

    private void jMenuItemCargarPorDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarPorDefectoActionPerformed
        // TODO add your handling code here:
        /*
        Punto f1 = new Punto((byte)0,(byte)0);
        Punto f2 = new Punto((byte)-2,(byte)0);
        
        Punto f3 = new Punto((byte)-2,(byte)0);
        Punto f4 = new Punto((byte)-2,(byte)2);
        
        Punto f5= new Punto((byte)-2,(byte)2);
        Punto f6= new Punto((byte)0,(byte)2);
        
        Punto f7= new Punto((byte)0,(byte)2);
        Punto f8= new Punto((byte)0,(byte)0);
        Recta rt1 = new Recta(f1,f2);
        Recta rt2 = new Recta(f3,f4);
        Recta rt3 = new Recta(f5,f6);
        Recta rt4 = new Recta(f7,f8);
        Poligono p= new Poligono();
        p.addLinea(rt1);
        p.addLinea(rt2);
        p.addLinea(rt3);
        p.addLinea(rt4);
        */
        listaDePuntos= new ListaPuntos();
        for (int i = 0; i < 3;i++){
            for(int j=0; j < 3; j++){
                Punto p1= new Punto((byte)i,(byte)j);
                
                listaDePuntos.agregarPunto(p1);
                
                
                
            }
        }
        //listaDePoligonos.agregarPoligono(p);
        
    }//GEN-LAST:event_jMenuItemCargarPorDefectoActionPerformed

    private void jMenuItemCargarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarPuntosActionPerformed
        // TODO add your handling code here:
         int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        try {
          // What to do with the file, e.g. display it in a TextArea
          try(FileReader fr = new FileReader(file.getAbsolutePath());
                BufferedReader  br = new BufferedReader(fr)){
                String sCurrentLine, aux = "";
                String[] aux1;
                getPuntos().clear();
                while ((sCurrentLine = br.readLine()) != null) {
                    aux1 = sCurrentLine.split(";");
                    aux += sCurrentLine + "\n";
                    getPuntos().add(new Punto(
                            Byte.parseByte(aux1[0].trim()),
                            Byte.parseByte(aux1[1].trim()))
                            
                            
                    );
                    
                    
                    System.out.println(aux1[0]+","+aux1[1]);
                }
                jTextAreaConsola.setText(aux);
            } catch (IOException e) {
                e.printStackTrace();
            }
          listaDePuntos= new ListaPuntos();
          for (int i=0; i <puntos.size();i++){
              listaDePuntos.agregarPunto(getPuntos().get(i));
          }
          
            
          
          
          
          
          
          
          jTextAreaConsola.read( new FileReader( file.getAbsolutePath() ), null );
        } catch (IOException ex) {
          System.out.println("Problema accediendo archivo"+file.getAbsolutePath());
          jTextAreaConsola.setText("Problema accediendo archivo"+file.getAbsolutePath());
          
        }
    } else {
        System.out.println("Acceso de archivo cancelado por usuario");
        jTextAreaConsola.setText("Acceso de archivo cancelado por usuario");
    }
        
        
    }//GEN-LAST:event_jMenuItemCargarPuntosActionPerformed

    private void jButtonMostrarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarPuntosActionPerformed
        // TODO add your handling code here:
        jTextAreaConsola.setText(listaDePuntos.toString());
        
    }//GEN-LAST:event_jButtonMostrarPuntosActionPerformed

    private void jButtonCrearRectasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearRectasActionPerformed
        JCrearRectas.getinstance().setVisible(true);
        
        
        
    }//GEN-LAST:event_jButtonCrearRectasActionPerformed

    private void jButtonCrearPoligonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPoligonosActionPerformed
        // TODO add your handling code here:
        
        
        
        
        JCrearPoligono.getInstance().setVisible(true);
        
        
    }//GEN-LAST:event_jButtonCrearPoligonosActionPerformed

    private void jButtonCrearSubPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearSubPoligonoActionPerformed
        // TODO add your handling code here:
        
        JSubPoligono.getInstance().setVisible(true);
        
        
        
    }//GEN-LAST:event_jButtonCrearSubPoligonoActionPerformed

    private void jButtonMayorPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMayorPerimetroActionPerformed
        // TODO add your handling code here:
        
        mayor=false;
        JPerimetro.getInstance().setVisible(true);
    }//GEN-LAST:event_jButtonMayorPerimetroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        jTextAreaConsola.setText(""+listaDeRectas.convertirARectas(listaDePuntos));
        
        
        
        
        
      
        
        
        
        
        
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonMenorPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenorPerimetroActionPerformed
        // TODO add your handling code here:
        mayor=true;
        JPerimetro.getInstance().setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jButtonMenorPerimetroActionPerformed

    private void jButtonRangoPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRangoPerimetroActionPerformed
        // TODO add your handling code here:
        
        JRango.getInstance().setVisible(true);
        
        
        
    }//GEN-LAST:event_jButtonRangoPerimetroActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        
        jTextAreaConsola.setText(listaDeRectas.toString());
        
        
        
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButtonColateralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColateralesActionPerformed
        // TODO add your handling code here:
        
        if(listaDePoligonos.totalPoligonos()!=0){
            
            JColaterales.getInstance().getjPoligono1().removeAllItems();//fix out of bounds
            for (int i = 0; i < listaDePoligonos.totalPoligonos();i++){

               JColaterales.getInstance().getjPoligono1().addItem("Poligono "+(i+1));
            }


            JColaterales.getInstance().getjPoligono2().removeAllItems();//fix out of bounds
            for (int i = 0; i < listaDePoligonos.totalPoligonos();i++){

               JColaterales.getInstance().getjPoligono2().addItem("Poligono "+(i+1));
            }
        
        }
        JColaterales.getInstance().setVisible(true);
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonColateralesActionPerformed

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonColaterales;
    private javax.swing.JButton jButtonCrearPoligonos;
    private javax.swing.JButton jButtonCrearRectas;
    private javax.swing.JButton jButtonCrearSubPoligono;
    private javax.swing.JButton jButtonListaSubPoligonos;
    private javax.swing.JButton jButtonMayorPerimetro;
    private javax.swing.JButton jButtonMenorPerimetro;
    private javax.swing.JButton jButtonMostrarLista;
    private javax.swing.JButton jButtonMostrarPuntos;
    private javax.swing.JButton jButtonPoligonoPorIndice;
    private javax.swing.JButton jButtonRangoPerimetro;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCargarPorDefecto;
    private javax.swing.JMenuItem jMenuItemCargarPuntos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaConsola;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
